title: smr
author: find me
email: sm.kazemi73@gmail.com
description: my tech blog

github_username: smkazemi
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:

# google_analytics:
# disqus_shortname:

blog_theme: auto

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag

theme: jekyll-theme-cayman
